--/* files in .csv format and imported file into sql server as a flat file.
--create database as sales data
use [sales data]

--DATA PREPARATION QUESTION

--Q1.. WHAT IS THE TOTAL NO OF ROWS IN EACH OF THE THREE TABLES IN THE DATABASE ?

SELECT COUNT(CUSTOMER_ID) AS NO_OF_CUST FROM [dbo].[customer data]
SELECT COUNT(prod_cat) AS NO_OF_INFO FROM [dbo].[product_info]
SELECT COUNT(TRANSACTION_ID) AS NO_OF_TRANS FROM [dbo].[transactions]

--Q2..WHAT IS THE TOTAL NO OF TRANSACTION THAT HAVE RETURNS?

 SELECT COUNT(TRANSACTION_ID) AS [NO. OF RETURNS] FROM transactions
 WHERE QTY < 0



-- Q3.. CONVERSION OF DATES ?

SELECT CONVERT(date, tran_date, 105) as DATE From transactions UNION
SELECT CONVERT(date, DOB, 105) from [dbo].[customer data]

-- Q4.. TIME RANGE OF TRANSACTION DATA ?

SELECT 
DATEDIFF(YEAR, min(CONVERT(Date, tran_date, 105)), max(CONVERT(Date, tran_date, 105))) as year_diff, 
DATEDIFF(DAY, min(CONVERT(Date, tran_date, 105)), max(CONVERT(Date, tran_date, 105))) as days_diff,
DATEDIFF(MONTH, min(CONVERT(Date, tran_date, 105)), max(CONVERT(Date, tran_date, 105))) as month_diff
from [dbo].[Transactions]


-- Q5.. PRODUCT CATEGORY DOES THE SUB CATEGORY DIY BELONGS TO ?

 SELECT prod_cat, prod_cat_code FROM [dbo].[product_info]
 WHERE prod_subcat = 'DIY'


-- DATA ANALYSIS

-- Q1.. WHICH CHANNEL IS MOST FREQUENTLY USED FOR TRANSACTIONS ?

   SELECT TOP 1 Store_type, COUNT(Store_type) AS COUNT_OF_FREQ FROM [dbo].[transactions]
   GROUP BY Store_type
   ORDER BY COUNT(Store_type) DESC

-- Q2.. WHAT IS COUNT OF MALE AND FEMALE CUST IN DATABASE?

 SELECT Gender, COUNT(GENDER) AS COUNT_FREQ from [dbo].[customer data]
 WHERE Gender IN ('M','F')
 GROUP BY Gender

--Q3.. FROM WHICH CITY DO WE HAVE MAX NO. OF CUSTOMERS AND HOW MANY?

 SELECT TOP 1 * FROM (
 SELECT city_code, COUNT([customer_Id]) AS COUNT_CUSTOMER 
 FROM [dbo].[customer data]
 GROUP BY city_code) TT
 ORDER BY COUNT_CUSTOMER DESC

-- Q4.. HOW MANY SUB-CATEGORIES ARE THERE UNDER BOOKS CATEGORY?
   SELECT COUNT(prod_subcat) AS CNT_SUB_CAT_BOOKS FROM [dbo].[product_info]
   WHERE prod_cat = 'Books'


-- Q5.. WHAT IS THE MAXIMUM QUANTITY OF PRODUCT EVER ORDERED?
   SELECT MAX(CAST(Qty AS INT)) AS MAX_QTY FROM [dbo].[transactions]


-- Q6.. WHAT IS THE NET TOTAL REVENUE GENERATED IN CATEGORY ELECTRONICS AND BOOKS?

SELECT COUNT(total_amt) AS REVENUE_EB 
FROM transactions
INNER JOIN [dbo].[product_info] ON [dbo].[product_info].prod_cat_code = [dbo].[Transactions].prod_cat_code
AND product_info .prod_sub_cat_code = [dbo].[Transactions].prod_subcat_code
WHERE [prod_cat] = 'Books' OR [prod_cat] = 'Electronics'


-- Q7.. HOW MANY CUSTOMERS HAVE > 10 TRANS WITH US EXCLUDING RETURNS?

SELECT COUNT([customer_Id]) AS CNT_CUST , [customer_Id]
FROM  [dbo].[customer data]
LEFT JOIN [dbo].[transactions] ON [dbo].[Transactions].cust_id = [dbo].[customer data].customer_Id
WHERE CAST(total_amt AS float) > 0
GROUP BY [customer_Id]
HAVING COUNT([customer_Id]) > 10

--Q8.. WHAT IS COMBINED REVENUE EARNED FROM ELECTRONICS AND CLOTHING FROM FLAGSHIP STORES?

 sELECT SUM(CAST(total_amt AS float)) AS REVENUE_EC
FROM [dbo].[transactions]
LEFT JOIN [dbo].[product_info] ON [dbo].[product_info].prod_cat_code = [dbo].[Transactions].prod_cat_code
AND [dbo].[product_info].prod_sub_cat_code = [dbo].[Transactions].prod_subcat_code
WHERE ([prod_cat] = 'Clothing' OR [prod_cat] = 'Electronics')
and Store_type = 'Flagship store'


--Q9. WHAT IS THE TOTAL REVENUE GENERATED FROM MALE CUST IN ELECTRONICS CATEGORY?
-- OUTPUT SHOULD DISPLAY TOTAL REVENUE BY PROD SUB CAT

   SELECT SUM(CAST(CASE WHEN Gender = 'M' AND prod_cat= 'Electronics' THEN total_amt END AS float)) AS REV_MALE
   FROM [dbo].[customer data]T1
   INNER JOIN TBL_TRANS_CS T2 ON T1.customer_Id = T2.cust_id
   INNER JOIN product_info T3 ON T2.prod_cat_code = T3.prod_cat_code AND T2.prod_subcat_code = T3.prod_sub_cat_code


-- Q10.. WHAT IS THE % OF SALES AND RETURNS BY PRODUCT SUB-CATEGORY ?
-- DISPLAY ONLY TOP 5 SUBCATEGORIES IN TERM OF SALES

SELECT TOP 5 [prod_subcat], SUM(CASE WHEN (CAST(total_amt AS float)) > 0 THEN (CAST(total_amt AS float)) ELSE 0 END) *100 / 
(SELECT SUM(CAST(total_amt AS float)) FROM   [dbo].[Transactions] WHERE (CAST(total_amt AS float)) > 0) AS SALES , 
SUM(CASE WHEN (CAST(total_amt AS float)) < 0 THEN (CAST(total_amt AS float)) ELSE 0 END) *100 / 
(SELECT SUM(CAST(total_amt AS float)) FROM   [dbo].[Transactions] WHERE (CAST(total_amt AS float)) < 0) AS RETURNS
FROM [dbo].[Transactions] 
INNER JOIN [dbo].[product_info] ON [dbo].[product_info].prod_cat_code = [dbo].[Transactions].prod_cat_code 
AND [dbo].[product_info].prod_sub_cat_code = [dbo].[Transactions].prod_subcat_code 
GROUP BY [prod_subcat]

-- Q11.. FOR ALL CUSTOMERS AGED BETWEEN 25 TO 35 YEARS FIND OUT WHAT IS THE 
-- NET TOTAL REVENUE GENERATED BY THESE CONSUMERS IN LAST 30 DAYS FROM MAX TRANSACTION DATE AVAILBLE IN THE DATA?


SELECT SUM(CAST(total_amt AS float)) TBL_REVENUE FROM [dbo].[Transactions] 
INNER JOIN [dbo].[customer data] ON [dbo].[customer data].customer_Id = [dbo].[Transactions].cust_id
WHERE DATEDIFF(YEAR, CONVERT(date, DOB, 105), CONVERT(date, tran_date, 105)) BETWEEN 25 AND 35
AND DATEADD(DAY, -30, (SELECT MAX(CONVERT(date, tran_date, 105)) FROM [dbo].[Transactions])) < CONVERT(date, tran_date, 105)

-- Q.. 12 WHICH PRODUCT CATEGORY HAS SEEN MAXIMUM RETURNS IN THE LAST THREE MONTHS OF TRANSACTION?

SELECT TOP 1 SUM(CAST(total_amt AS float)) TBL_RETURNS, [prod_cat] FROM [dbo].[Transactions] 
INNER JOIN [dbo].[customer data] ON [dbo].[customer data].customer_Id = [dbo].[Transactions].cust_id
INNER JOIN [dbo].[product_info] ON [dbo].[product_info].prod_cat_code = [dbo].[Transactions].prod_cat_code
AND product_info.prod_sub_cat_code = [dbo].[Transactions].prod_subcat_code
WHERE CAST(total_amt AS float) < 0
AND DATEADD(MONTH, -3, (SELECT MAX(CONVERT(date, tran_date, 105)) FROM [dbo].[Transactions])) < CONVERT(date, tran_date, 105)
GROUP BY [prod_cat]
ORDER BY TBL_RETURNS



-- Q13.. WHICH STORE TYPE SELLS MAXIMUM PRODUCT BY SALES AND BY QUANTITY SOLD?

SELECT TOP 1 SUM(CAST(Qty AS INT)) AS QUANTITY, SUM(CAST(total_amt AS FLOAT)) AS TOTAL, Store_type
 FROM [dbo].[transactions]
 GROUP BY Store_type
 ORDER BY QUANTITY DESC, TOTAL DESC 


-- Q14.. WHAT ARE THE CATEGORIES FOR WHICH THE AVERAGE REVENUE IS GREATER THAN OVERALL avg.?

 
SELECT AVG(CAST(total_amt AS FLOAT)) as AVERAGE , [prod_cat] FROM [dbo].[Transactions] 
LEFT JOIN product_info on product_info.prod_cat_code = [dbo].[Transactions].prod_cat_code
AND product_info.prod_sub_cat_code = [dbo].[Transactions].prod_subcat_code
GROUP BY [prod_cat]
HAVING AVG(CAST(total_amt AS FLOAT)) > (SELECT AVG(CAST(total_amt AS FLOAT)) as average FROM [dbo].[transactions])

-- Q15.. FIND THE AVG AND TOTAL REVENUE BY EACH SUBACTEGORY FOR THE CATEGORY WHICH ARE AMONG TOP 5 IN TERMS OF QUANTITY SOLD?

SELECT [prod_subcat], AVG(CAST(total_amt AS FLOAT)) as AVERAGE, SUM(CAST(total_amt AS FLOAT)) as TOTAL FROM [dbo].[Transactions]
LEFT JOIN [dbo].[product_info] ON [dbo].[product_info].prod_cat_code = [dbo].[Transactions].prod_cat_code 
AND [dbo].[product_info].prod_sub_cat_code = [dbo].[Transactions].prod_subcat_code
WHERE [prod_cat] IN (SELECT TOP 5 [prod_cat]
FROM [dbo].[transactions] 
LEFT JOIN [dbo].[product_info] on [dbo].[product_info].prod_cat_code = [dbo].[Transactions].prod_cat_code
GROUP BY [prod_cat]
 ORDER BY SUM(CAST(Qty AS INT)) DESC)
 GROUP BY [prod_subcat]

